"""add status priority assigned_to to tickets

Revision ID: 85ca73bec46e
Revises: 0d1a27f0811f
Create Date: 2026-01-12 21:01:22.289715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85ca73bec46e'
down_revision: Union[str, Sequence[str], None] = '0d1a27f0811f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('tickets', sa.Column('priority', sa.String(length=20), nullable=False))
    op.add_column('tickets', sa.Column('assigned_to_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'users', ['assigned_to_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'assigned_to_id')
    op.drop_column('tickets', 'priority')
    op.drop_column('tickets', 'status')
    # ### end Alembic commands ###
